class ValidationCodes (object):
    """
    Error codes class.
    """
    __slots__ = ()
    SUCCESS = 100
    NO_ACTIVE_OR_PAUSED_READING_WAS_FOUND = 101
    NO_BOOK_WAS_FOUND_WITH_THE_GIVEN_ISBN_CODE = 102
    BOOK_HAS_ALREADY_BEEN_ADDED_TO_BOOK_SHELF = 103
    EMAIL_HAS_ALREADY_BEEN_ADDED_TO_APPLICATION = 104
    WRONG_VALIDATION_CODE = 105
    EMAIL_NOT_CONFIRMED = 106
